global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs: [{ targets: ["prometheus:9090"] }]
  - job_name: cadvisor
    static_configs: [{ targets: ["cadvisor:8080"] }]
  - job_name: dcgm
    static_configs: [{ targets: ["dcgm-exporter:9400"] }]
  - job_name: traefik
    static_configs: [{ targets: ["traefik:8080"] }]
  - job_name: grafana
    metrics_path: /metrics
    static_configs: [{ targets: ["grafana:3000"] }]
  - job_name: "myspinbot-backend"
    static_configs: [{ targets: ["api:3000"] }]
  - job_name: "redis"
    metrics_path: /metrics
    static_configs: [{ targets: ["redis-exporter:9121"] }]
  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]
