http:
  serversTransports:
    truenasInsecure:
      insecureSkipVerify: true
  middlewares:
    dashboard-auth:
      basicauth:
        usersfile: /etc/traefik/htpasswd
        realm: "MySpinBot Secure Zone"
        removeHeader: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/wildcard-myspinbot.local.crt
        keyFile: /certs/wildcard-myspinbot.local.key